# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Tyler Blake
tagline:          ''
description:      'Stay a while and listen.'
url:              https://tylerablake.github.io/website
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Tyler Blake'
  url:            https://twitter.com/TylerBlakeLOU
  twitterUrl:            https://twitter.com/TylerBlakeLOU  

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/tylerablake

twitter:
    url:            http://twitter.com/TylerBlakeLOU

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: tylerablake