# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tyler Blake
tagline:          Software Journeyman
description:      'Welcome to my website, where we go on quests through software development!'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Tyler Blake'
  url:            https://twitter.com/TylerBlakeLOU

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tylerablake
