# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Dev Quests
tagline:          Software Devlopment
description:      'Dev Quests, where we go on quests in software development! Made by <a href="https://twitter.com/TylerBlakeLOU" target="_blank">Tyler Blake</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           Tyler Blake
  url:            https://twitter.com/TylerBlakeLOU

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tylerablake
